# Generated by Django 5.1.5 on 2025-01-31 17:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="guestuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="+1234567890",
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
                (
                    "knows",
                    models.CharField(
                        choices=[
                            ("1", "Bride (Amy)"),
                            ("2", "Groom (Kevin)"),
                            ("3", "Both"),
                        ],
                        max_length=1,
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
