# Generated by Django 5.1.5 on 2025-04-24 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="1234566789", null=True),
                ),
                (
                    "knows",
                    models.CharField(
                        choices=[
                            ("1", "Bride (Amy)"),
                            ("2", "Groom (Kevin)"),
                            ("3", "Both"),
                        ],
                        max_length=1,
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
                ("code", models.CharField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="invitation_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(null=True)),
                ("attend", models.BooleanField(default=False)),
                (
                    "party",
                    models.BooleanField(
                        default=False,
                        help_text="Please check if you plan on staying for after party",
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("self", "Just Myself"),
                            ("family", "Family"),
                            ("other", "Family Friend"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("number_of_guests", models.IntegerField(blank=True, null=True)),
                (
                    "guest_names",
                    models.CharField(
                        blank=True,
                        help_text="Please provide all first and last names seperated by comma(s)",
                        null=True,
                    ),
                ),
                (
                    "invite",
                    models.BooleanField(
                        default=False, help_text="Do you want a physical invitation?"
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
