# Generated by Django 5.1.5 on 2025-04-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation_info',
            name='group_type',
            field=models.CharField(blank=True, choices=[('self', 'Just Myself'), ('couple', 'My Spouse and I'), ('family', 'Family'), ('other', 'Family Friend')], max_length=20, null=True),
        ),
    ]
