# Generated by Django 5.1.5 on 2025-01-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0002_invitation_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation_info",
            name="guest_names",
            field=models.CharField(
                help_text="Please provide all first and last names seperated by comma(s)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invitation_info",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Include Apt # if applicable",
                max_length=255,
                null=True,
            ),
        ),
    ]
