# Generated by Django 5.1.5 on 2025-02-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0003_invitation_info_guest_names_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation_info",
            name="invitation",
            field=models.BooleanField(
                default=False, help_text="Check box for physical invitation"
            ),
        ),
    ]
