# Generated by Django 5.1.5 on 2025-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0004_alter_invitation_info_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation_info",
            name="invite",
            field=models.BooleanField(
                default=False, help_text="Do you want a physical invitation?"
            ),
        ),
    ]
