# Generated by Django 5.1.5 on 2025-04-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0005_invitation_info_invite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation_info",
            name="address",
        ),
        migrations.RemoveField(
            model_name="invitation_info",
            name="city",
        ),
        migrations.RemoveField(
            model_name="invitation_info",
            name="invitation",
        ),
        migrations.RemoveField(
            model_name="invitation_info",
            name="state",
        ),
        migrations.RemoveField(
            model_name="invitation_info",
            name="zip_code",
        ),
    ]
