# Generated by Django 5.1.5 on 2025-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0006_remove_invitation_info_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestuser",
            name="code",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="invitation_info",
            name="group_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self", "Just Myself"),
                    ("family", "Family"),
                    ("other", "Family Friend"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invitation_info",
            name="guest_names",
            field=models.CharField(
                blank=True,
                help_text="Please provide all first and last names seperated by comma(s)",
                null=True,
            ),
        ),
    ]
