# Generated by Django 5.1.5 on 2025-04-23 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0007_guestuser_code_alter_invitation_info_group_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation_info",
            name="choice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invitation_info",
            name="name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="invitation_info",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
