# Generated by Django 5.1.5 on 2025-04-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0008_invitation_info_choice_invitation_info_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitation_info",
            old_name="choice",
            new_name="attend",
        ),
    ]
